### ISSUE TITLE
jupyter kernel crashes with doc example

### ISSUE THREAD

**Issue by rlloretb** [metab0t/PyOptInterface#16]
```
import pyoptinterface as poi
from pyoptinterface import highs

model = highs.Model()

x = model.add_variable(lb=0, ub=1, domain=poi.VariableDomain.Continuous, name="x")
y = model.add_variable(lb=0, ub=1, domain=poi.VariableDomain.Integer, name="y")

con = model.add_linear_constraint(x+y, poi.Geq, 1.2, name="con")

obj = 2*x
model.set_objective(obj, poi.ObjectiveSense.Minimize)

model.set_model_attribute(poi.ModelAttribute.Silent, False)
model.optimize()

print(model.get_model_attribute(poi.ModelAttribute.TerminationStatus))
# TerminationStatusCode.OPTIMAL

x_val = model.get_value(x)
# 0.2

y_val = model.get_value(y)
# 1.0
```

When running this example, Jupyter kernel crashes in model.optimize()

> The Kernel crashed while executing code in the current cell or a previous cell. 
Please review the code in the cell(s) to identify a possible cause of the failure. 
Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. 
View Jupyter [log](command:jupyter.viewOutput) for further details.

> 17:39:18.153 [error] Disposing session as kernel process died ExitCode: 3221225477, Reason: 

Windows 11, VSCode, Python 3.11.6

**Comment by rlloretb** [comment]
`INFO:root:Loaded HiGHS library: [c:\Users\user\miniconda3\envs\my_env\Lib\site-packages\highsbox\highs_dist\bin\highs.dll](file:///C:/Users/user/miniconda3/envs/my_env/Lib/site-packages/highsbox/highs_dist/bin/highs.dll)`

**Comment by metab0t** [comment]
This is weird, PyOptInterface has loaded HiGHS correctly. I am not sure why it only fails in Jupyter. It works fine in Jupyter notebook of my VSCode. 

Have you tried other jupyter environments, like the jupyter notebook in browser or in PyCharm?

**Comment by rlloretb** [comment]
On google colab (browser) it does work well.

**Comment by rlloretb** [comment]
On a separate new environment it does work well.
