### ISSUE TITLE
Get variable's and constraint's basis and slack information

### ISSUE THREAD

**Issue by zhouxinsheng** [metab0t/PyOptInterface#18]
In some of my cases, more solution details are needed, it would be more convenient if such attributes as Variable.VBasis/Constraint.CBasis/Constraint.Slack in Gurobi (Variable.Basis/Constraint.Basis/Constraint.Slack in COPT) be supported in pyoptinterface.

**Comment by metab0t** [comment]
See https://metab0t.github.io/PyOptInterface/gurobi.html#attribute and https://metab0t.github.io/PyOptInterface/copt.html#information to get more information of the variable/constraint in Gurobi and COPT.
