### ISSUE TITLE
HiGHS features

### ISSUE THREAD

**Issue by Thell** [metab0t/PyOptInterface#20]
Hello! First, let me say 👍 for the project.

Next... I have a question. On the ABOUT page one of the bullet points highlights the following feature.

> Low overhead to modify and re-solve the problem incrementally (including adding/removing variables/constraints, changing objective function, etc.)

Modify and resolve is of particular interest to me but looking at the features list for HiGHS I see that variable assignment is supported for  it even though HiGHS supports it and partial assignment warm starts. As mentioned at the end of [this Julia JuMP discussion](https://discourse.julialang.org/t/infeasible-warmstart-with-jump-highs/106869/8).

I don't know of _any_ python interface to HiGHS that supports a modify/re-solve for HiGHS, are there any plans for adding that for HiGHS in PyOptInterface?

**Comment by metab0t** [comment]
PyOptInterface does support modify-and-resolve for HiGHS like add/remove/modify variable or constraint

I think you may want to set the [`PrimalStart`](https://metab0t.github.io/PyOptInterface/variable.html#variable-attributes) attribute of a variable?

**Comment by Thell** [comment]
Excellent, thanks. I had stopped looking when I saw the red X but will now look into the PrimalStart. Let's close this for now and if PrimalStart doesn't work out I'll let you know.

![image](https://github.com/user-attachments/assets/c67b7354-b66b-4676-ad0f-576fceea3797)

**Comment by jajhall** [comment]
> I don't know of _any_ python interface to HiGHS that supports a modify/re-solve for HiGHS, are there any plans for adding that for HiGHS in PyOptInterface?

The native `highspy` interface allows efficient modify/re-solve for HiGHS.
