### ISSUE TITLE
Suppress output that is being printed when model is loaded

### ISSUE THREAD

**Issue by TUM-Doepfert** [metab0t/PyOptInterface#26]
Hey there!

Thank you very much for this performant library that is easy to use.

I work on an agent-based tool that creates optimization problems dynamically for each agent and time step. When I create the first model I get the following output once:

![image](https://github.com/user-attachments/assets/777ca91f-123a-4d51-819a-46fe2f97ee44)

I have tried to resolve it by creating the environment first and setting the OutputFlag to 0, similar to the approach mentioned in this [gurobi post](https://support.gurobi.com/hc/en-us/community/posts/360068141811-Messages-being-printed-to-standard-output-when-library-is-loaded). Unfortunately, it does not suppress the initial output.

Is there already a way to suppress this output and I just missed it? If not, would it be possible to implement this functionality?

Thank you very much in advance!

**Comment by metab0t** [comment]
Thanks for using POI!

The code you want is similar in POI:
```python
import pyoptinterface as poi
from pyoptinterface import gurobi

env = gurobi.Env(empty=True)
env.set_raw_parameter("OutputFlag", 0)
env.start()

model = gurobi.Model(env)
```

**Comment by TUM-Doepfert** [comment]
Thank you for your swift reponse! I tried something like that but unfortunately it still prints it out the first instance the model is created as shown in the original post. This is the code right now:

```python    
def get_model(self, **kwargs):
    env = gurobi.Env(empty=True)
    env.set_raw_parameter("OutputFlag", 0)
    env.start()
    model = gurobi.Model(env)
    model.set_model_attribute(poi.ModelAttribute.Silent, True)
    model.set_raw_parameter("OutputFlag", 0)
    model.set_raw_parameter("LogToConsole", 0)
    return model
```

**Comment by TUM-Doepfert** [comment]
Thanks for the clarification! I thought that I only needed to suppress it the first time a model gets created, however, it will print out the information whenever a new model gets created and the information has not been printed to the console. By including it in all model creation functions, it shows no output as desired.

Thank you once again for your help!

**Comment by metab0t** [comment]
By the way, you should reuse the silent `env` if you want to create a lot of models.

According to https://www.gurobi.com/documentation/current/refman/session_boundaries.html:

> If your program repeatedly creates, solves, and destroys optimization models, we strongly recommend that you do so within a single Gurobi environment. Creating a Gurobi environment incurs overhead, ranging anywhere from a quick local license check all the way to spinning up a machine on the cloud. By reusing a single environment, you avoid paying this overhead multiple times.

**Comment by TUM-Doepfert** [comment]
Thank you for the information! I will adapt the code accordingly.
