### ISSUE TITLE
`function GRBemptyenv is not loaded correctly`

### ISSUE THREAD

**Issue by staadecker** [metab0t/PyOptInterface#31]
Running `from pyoptinterface import gurobi` gives two error messages:

```
function GRBemptyenv is not loaded correctly
function GRBloadenv is not loaded correctly
```

I understand these probably can be safely ignored however it would be nice as I work on integrating PyOptInterface in my library that users aren't distracted/confused by error messages.

**Comment by metab0t** [comment]
Are you using Gurobi 12?
There is a bug in their dynamic library https://docs.gurobi.com/projects/optimizer/en/current/reference/releasenotes/knownbugs.html#missing-symbols-in-shared-library-libgurobi120

I can suppress this for 12.0.0 as a special case

**Comment by staadecker** [comment]
Aha. I was using 12. Since it's just a temporary issue until the next release I wouldn't worry about it!
